### ISSUE TITLE
Tooltips are rendered as their own windows.

### ISSUE THREAD

**Issue by colemickens** [SirCmpwn/sway#446] opened 2016-01-15 05:43 UTC
Hover over anything with a tooltip. The tooltip is rendered as a new window.

![Screenshot](http://i.imgur.com/2Y5YUzc.png)

Maybe this is specific to XWayland client applications? I'm not sure.

**Comment by SirCmpwn** [comment] 2016-01-15 09:48
Duplicate of https://github.com/Cloudef/wlc/issues/104

**Closed by SirCmpwn** 2016-01-15 09:48 UTC
