### ISSUE TITLE
X11 Regressions.

### ISSUE THREAD

**Issue by Luminarys** [SirCmpwn/sway#78] opened 2015-08-19 03:22 UTC
It seems as if multiple output workspaces have somehow regressed in X, and workspaces have been imaginarily linked together(opening a view in one workspace somehow inserts it into the tree of another). There are also numerous segfaults occuring as a result of this.

**Comment by Luminarys** [comment] 2015-08-19 04:46
This seems to be caused by glitches in the `get_focused_container` function as well as active_workspace not being set properly.

**Comment by Luminarys** [comment] 2015-08-19 05:13
Since @taiyu-len doesn't seem to be experiencing these glitches, this might be a one-of problem for me. Log info for spawning two workspaces:
```
Compositor is ready, executing cmds in queue
Setting focus to 0x24dcf10:1
Handling command 'exec urxvt'
Executing urxvt
Adding new view 3:urxvt to container 0x24db470 2
Adding 0x25d0d80 (4, 0x0) to 0x24db470 (2, 606x983)
Setting focus to 0x25d0d80:3
Arranging layout for 0x24dcf10
Arranging workspace #0 at 10, 10
Arranging layout for 0x24db470
Arranging 0x24db470 horizontally
Calculating arrangement for 0x25d0d80:4 (will receive 1.00 of 606)
Set view to 586 x 963 @ 20, 20
focus:R|(0x60cba0)(p:(nil))(f:0x24dcf10)(h:-1)Type:Root|layout:NONE|w:0|h:0|x:0|y:0|vis:f|wgt:0|name:(null)|children:2
|focus:X|(0x24dcf10)(p:0x60cba0)(f:0x24db470)(h:1)Type:Output|layout:NONE|w:626|h:1003|x:0|y:0|vis:f|wgt:1|name:None-0|children:1
|-focus:W|(0x24db470)(p:0x24dcf10)(f:0x25d0d80)(h:-1)Type:Workspace|layout:Horiz|w:606|h:983|x:10|y:10|vis:t|wgt:1|name:web|children:1
|--focus:F|(0x25d0d80)(p:0x24db470)(f:(nil))(h:3)Type:View|layout:NONE|w:606|h:983|x:10|y:10|vis:t|wgt:1|name:urxvt|children:0
|focus:X|(0x25ba650)(p:0x60cba0)(f:(nil))(h:2)Type:Output|layout:NONE|w:611|h:1003|x:0|y:0|vis:f|wgt:1|name:None-1|children:1
|-focus:F|(0x25a37a0)(p:0x25ba650)(f:(nil))(h:-1)Type:Workspace|layout:Horiz|w:591|h:983|x:10|y:10|vis:t|wgt:1|name:term|children:0
Setting focus to 0x25d0d80:3
Setting focus to 0x25d0d80:3
Setting focus to 0x25ba650:2
Handling command 'exec urxvt'
Executing urxvt
get_focused_container unable to find container
Adding new view 4:urxvt to container 0x24db470 2
Adding 0x25b5960 (4, 0x0) to 0x24db470 (2, 606x983)
Setting focus to 0x25b5960:4
Setting focus to 0x24dcf10:1
Arranging layout for 0x24dcf10
Arranging workspace #0 at 10, 10
Arranging layout for 0x24db470
Arranging 0x24db470 horizontally
Calculating arrangement for 0x25d0d80:4 (will receive 0.50 of 606)
Set view to 283 x 963 @ 20, 20
Calculating arrangement for 0x25b5960:4 (will receive 0.50 of 606)
Set view to 283 x 963 @ 323, 20
focus:R|(0x60cba0)(p:(nil))(f:0x24dcf10)(h:-1)Type:Root|layout:NONE|w:0|h:0|x:0|y:0|vis:f|wgt:0|name:(null)|children:2
|focus:X|(0x24dcf10)(p:0x60cba0)(f:0x24db470)(h:1)Type:Output|layout:NONE|w:626|h:1003|x:0|y:0|vis:f|wgt:1|name:None-0|children:1
|-focus:W|(0x24db470)(p:0x24dcf10)(f:0x25b5960)(h:-1)Type:Workspace|layout:Horiz|w:606|h:983|x:10|y:10|vis:t|wgt:1|name:web|children:2
|--focus:F|(0x25d0d80)(p:0x24db470)(f:(nil))(h:3)Type:View|layout:NONE|w:303|h:983|x:10|y:10|vis:t|wgt:1|name:urxvt|children:0
|--focus:F|(0x25b5960)(p:0x24db470)(f:(nil))(h:4)Type:View|layout:NONE|w:303|h:983|x:313|y:10|vis:t|wgt:1|name:urxvt|children:0
|focus:X|(0x25ba650)(p:0x60cba0)(f:(nil))(h:2)Type:Output|layout:NONE|w:611|h:1003|x:0|y:0|vis:f|wgt:1|name:None-1|children:1
|-focus:F|(0x25a37a0)(p:0x25ba650)(f:(nil))(h:-1)Type:Workspace|layout:Horiz|w:591|h:983|x:10|y:10|vis:t|wgt:1|name:term|children:0
Setting focus to 0x25d0d80:3
Setting focus to 0x24db470:-1
Setting focus to 0x25d0d80:3
Setting focus to 0x25d0d80:3
```

Crashes such as this also happen:
```
focus:R|(0x60cba0)(p:(nil))(f:0x158d400)(h:-1)Type:Root|layout:NONE|w:0|h:0|x:0|y:0|vis:f|wgt:0|name:(null)|children:2
|focus:X|(0x14e21e0)(p:0x60cba0)(f:0x14abfc0)(h:1)Type:Output|layout:NONE|w:626|h:1003|x:0|y:0|vis:f|wgt:1|name:None-0|children:1
|-focus:W|(0x14abfc0)(p:0x14e21e0)(f:(nil))(h:-1)Type:Workspace|layout:Horiz|w:606|h:983|x:10|y:10|vis:t|wgt:1|name:web|children:0
|focus:X|(0x158d400)(p:0x60cba0)(f:(nil))(h:2)Type:Output|layout:NONE|w:611|h:1003|x:0|y:0|vis:f|wgt:1|name:None-1|children:1
|-focus:F|(0x15ada40)(p:0x158d400)(f:(nil))(h:-1)Type:Workspace|layout:Horiz|w:591|h:983|x:10|y:10|vis:t|wgt:1|name:term|children:0
Setting focus to 0x14abfc0:-1
Setting focus to 0x14e21e0:1
get_focused_container unable to find container
Mouse button 272 pressed
Setting focus to 0x14abfc0:-1
get_focused_container unable to find container
Mouse button 272 released
Setting focus to 0x14abfc0:-1
Setting focus to 0x158d400:2
get_focused_container unable to find container
Mouse button 272 pressed

Program received signal SIGSEGV, Segmentation fault.
0x0000000000405032 in handle_pointer_button (view=0, time=23959160, modifiers=0x7ffff7dd9918 <wlc+920>, button=272, state=WLC_BUTTON_STATE_PRESSED, origin=0x7fffffffe2e0) at /....../sway/handlers.c:460
460                     if (pointer->is_floating) {
```

**Comment by taiyu-len** [comment] 2015-08-19 05:33
problem with output not having focus set to its only child. fixed by making sure add_child sets focus when adding first child.

**Comment by SirCmpwn** [comment] 2015-08-19 12:34
I get the occasional problem like you originally described, but I haven't figured out the conditions for reproducing it yet.

**Comment by SirCmpwn** [comment] 2015-08-20 12:02
I haven't seen this again since my last comment. Anyone else able to repro?

**Comment by taiyu-len** [comment] 2015-08-20 12:14
should  be fixed it was cause by output not having a focus set `f:(nil))(h:2)Type:Output|`

**Closed** 2015-08-20 12:29 UTC
