### ISSUE TITLE
touchpad tap-to-click support

### ISSUE THREAD

**Issue by robotanarchy** [SirCmpwn/sway#365] opened 2015-12-19 14:21 UTC
Touchpad tap-to-click support would be nice :+1: 

From the libinput page on [tapping](http://wayland.freedesktop.org/libinput/doc/latest/tapping.html):
> Tapping can be enabled on a per-device basis. See [libinput_device_config_tap_set_enabled()](http://wayland.freedesktop.org/libinput/doc/latest/group__config.html#ga3caf860883d4e2e42b7842599da03e56) for details.

For the config, maybe something like this could work?
```
input $devicename tap-to-click
```

**Comment by SirCmpwn** [comment] 2015-12-19 14:21
Eventually I would like to have an input { } section in your config, like bar { }  and mode { } and such.

**Comment by onny** [comment] 2015-12-19 15:00
Uff, just recognized that my left mouse button on my laptop is broken ... I usually use the touchpad for clicking.

**Comment by somebears** [comment] 2015-12-19 15:18
Looking at the source of orbment (WM developed by the developer of wlc), it seems like libinput configuration is done in the WM

see:
https://github.com/Cloudef/orbment/blob/229a870dbbb9dbc66c137cf2747eab11acdf1a95/plugins/core-input/core-input.c

**Comment by SirCmpwn** [comment] 2015-12-19 15:19
Indeed, there's a wlc callback.

**Comment by onny** [comment] 2015-12-21 11:04
@somebears: Do you know any workaround or hack for sway? Not sure how to use this wlc callback ...

**Comment by somebears** [comment] 2015-12-21 14:01
I don't have the experience/knowledge for that, sorry.

I suspect, that it would work very similar to the orbment version. The problem is getting the device. I suspect that there is an event you can look for, as done in https://github.com/Cloudef/orbment/blob/b0d3016275222a6a27bbeae9f9344c8ea0d2690c/src/hooks.c

However, sway does not use anything similar as far as I can tell.

**Comment by colemickens** [comment] 2015-12-30 00:25
I've looked at Orbital and wlc and I kind of understand how Orbital supports this configuration.

@SirCmpwn Have you thought about what this might look like? I realize that each compositor owns the code that interacts with libinput, but I don't see any reason there couldn't be a small library that could be shared between Orbment/Sway/Gnome/whoever for configuring libinput devices.

Any compositor that wants to support this common configuration mechanism will utilize this library. In turn, Orbment and Sway would connect the wlc interface to it. The library would handle new input device events and would have it's own logic for parsing a per-input-device config file (XDG_CONFIG_DIR/libinput/devices/DEVICE_NAME). It's only job is to parse the input device configuration files and apply them when wlc reports a new device.

That would allow me to configure my input devices once per computer and have them operate the same under any compositor that supports this "standard".

Just a random idea I had. I've been toying with the notion of trying to hack Sway just enough to invert the scroll direction....

**Comment by SirCmpwn** [comment] 2015-12-30 03:21
I would really prefer if the input configuration was done in your sway config.

**Comment by progandy** [comment] 2015-12-30 08:52
@colemickens if you wish for a universal interface, I think you should define a wayland protocol extension which can be used to implement a configuration utility analog to setxkbmap/xinput. Static configuration can be kept in the sway config.

**Comment by colemickens** [comment] 2016-01-15 04:50
I have a branch with libinput modifications. These modifications allow you to control a number of things like natural scrolling click to type, disable while typing and more. I'm currently using it to enable natural scrolling, disable-while-typing on my touchpad, and using it to disable the touchscreen on my device (which prevents sway from crashing).

There is one small problem that keeps me from sending a pull request. libinput doesn't give a super great naming convention to devices, which makes it hard to select a good key to use for configuring a given input device. Orbment only allows you to configure libinput devices based on product/vendor id. But, for example, my touchpad and touchscreen have the same product/vendor id. Further, the `event#` identifier is inconsistent between boots, otherwise that would be usable.

Unfortunately, I've been told that the only way to do this, is by configuring against the full string'd device name/description that comes back from libinput. So, you'd have to do something like `input "0:0:Atmel Touchscreen XL1" tap off` in your configuration file. Which has it's own obvious problems, like the fact that the device names have spaces in them and I don't know if the config parsing code knows how to handle quoted strings.

The other option is to reach down to the udev device and try to allow for configurations that address "classes" of devices. Something like this:

```
input touchpad tap enable # enable tap to click
input touchscreen events disable # disable all events for this device
```

But then what if someone wants to configure two touchpads independently, etc...

@SirCmpwn  thoughts?

**Comment by SirCmpwn** [comment] 2016-01-15 09:49
Can we CRC-32 the device name strings and let you edit config files with them? We can log the CRCs and add an IPC command for listing input devices to make it easier on the user.

**Comment by mikkeloscar** [comment] 2016-01-15 17:21
I think it would be nice to support configuration for individual devices and for classes of devices. That way you can have a general config for touchpad devices, or you can customize it for a specific touchpad if you like.

I think device/name is a fine identifier, and the config parser can handle quoted strings just fine. :)

**Comment by SirCmpwn** [comment] 2016-01-15 18:19
I agree with that, @mikkeloscar.

**Comment by onny** [comment] 2016-01-15 22:01
Good point @mikkeloscar

**Comment by onny** [comment] 2016-01-17 22:37
Wohoo, the changes in the pull request are already working! Thank you colemickens!

**Comment by aouelete** [comment] 2016-01-24 01:40
Has anyone managed to get tap-to-click working on a Synaptics touchpad?
Running `swaymsg -t get_inputs` gives me:
```
[ { "identifier": "0:1:Power_Button" }, { "identifier": "0:6:Video_Bus" }, { "identifier": "3034:22297:Integrated_" }, { "identifier": "1:1:AT_Translated_Set_2_keyboard" }, { "identifier": "2:7:SynPS\/2_Synaptics_TouchPad" }, { "identifier": "2:10:TPPS\/2_IBM_TrackPoint" }, { "identifier": "6058:20564:ThinkPad_Extra_B" } ]
```
And I have this in my sway config:
```
input 2:7:SynPS\/2_Synaptics_TouchPad {
    tap enabled
    natural_scroll enabled
}
```
but this doesn't change anything.

**Comment by algmyr** [comment] 2016-01-24 01:45
@aouelete:
The slash shouldn't be escaped in the config.

**Comment by aouelete** [comment] 2016-01-24 01:46
Oh, ok. It seems to be working now. Thanks!

**Comment by mikkeloscar** [comment] 2016-02-24 21:31
I think everything here was solved long ago, so I'm closing this.

**Closed by mikkeloscar** 2016-02-24 21:31 UTC

**Comment by unihernandez22** [comment] 2020-10-30 02:35
So, how can I enable tap-to-click with libinput?

**Comment by colemickens** [comment] 2020-10-30 02:37
`man 5 sway-input`, search for "tap", look at the second hit:

```
       input <identifier> tap enabled|disabled
           Enables or disables tap for specified input device.
```

**Comment by unihernandez22** [comment] 2020-10-30 03:06
@colemickens thx, I found it on default config. And the manual has helped.

**Comment by nukeCrayon** [comment] 2022-08-16 10:14
> @aouelete: The slash shouldn't be escaped in the config.

thank you for this. it works for me now.
