### ISSUE TITLE
Bad char coding in window title

### ISSUE THREAD

**Issue by podhorsky-ksj** [SirCmpwn/sway#570] opened 2016-04-02 16:45 UTC
Hello,

There is bad char coding in window title bar, especialy when the window name contains chars, 
which are not in standard ascii.

I have seen something like this on screenshot of sway placed on code page of this project in title bar of firefox. Is this issue already known?

**Comment by mikkeloscar** [comment] 2016-04-02 17:08
Can you post a screenshot of the issue?

**Comment by TheBits** [comment] 2016-04-02 17:14
Title of Skype(R)(C)(TM) for example.

**Comment by mikkeloscar** [comment] 2016-04-02 17:33
Ok I see. I assume the problem is that the skype title isn't in UTF-8.

@Cloudef what encoding is the title we get from `wlc_view_get_title()` in?

**Comment by Cloudef** [comment] 2016-04-02 18:11
@mikkeloscar Good question, for wayland clients should be utf8, for X clients it can actually be anything since UTF8_STRING property atom isn't used (should be fixed to try that at least first)

**Comment by SirCmpwn** [comment] 2016-04-02 20:29
Just confirmed: works correctly for wayland windows. Incorrectly for x windows.

**Comment by Cloudef** [comment] 2016-04-02 21:01
I'll link to wlc

**Comment by Cloudef** [comment] 2016-04-02 21:02
#147

**Comment by Cloudef** [comment] 2016-06-02 19:39
Should be fixed in wlc now.

**Comment by SirCmpwn** [comment] 2016-06-02 19:48
Thanks @Cloudef!

**Closed by SirCmpwn** 2016-06-02 19:48 UTC
