### ISSUE TITLE
Issues with Ibus character select popup window

### ISSUE THREAD

**Issue by soleera** [SirCmpwn/sway#1225] opened 2017-05-20 01:39 UTC
When using Ibus with kcc, I cannot use the kanji conversion popup window; pressing space twice instead causes the window to flash up on the right hand side of my screen and then dissapear, deleting whatever was selected for conversion. A similar thing happens with libpinyin, however in this case I can't type anything at all because the conversion window tries to open as soon as I start typing.

Any ideas as to what could be causing this?

**Comment by SirCmpwn** [comment] 2017-05-20 01:42
Dupe of #873. Basically, ibus is really X-specific and it'll be difficult for Sway to support it - at least until we implement the relevant protocols (and even then, it'll take some work). I'm able to type in Japanese fairly well - 日本語でいいです, but it requires some patience and guesswork tbh.

**Comment by SirCmpwn** [comment] 2017-05-20 01:42
Use `ibus-daemon -drx`

**Closed by SirCmpwn** 2017-05-20 01:42 UTC

**Comment by manonthemat** [comment] 2018-09-13 21:07
@saih792, did you ever get your issue resolved (using ibus-daemon or by other means)?
