### ISSUE TITLE
[bar.c:230] failed to dispatch wl: 32

### ISSUE THREAD

**Issue by Kamiyaa** [SirCmpwn/sway#1002] opened 2016-12-18 17:49 UTC
Not exactly sure what happened, but sway exited and I was thrown back into tty
```
12/18/16 11:30:39 - [main.c:46] [wlc] logind: session control granted
12/18/16 11:30:39 - [main.c:46] [wlc] Running on vt 1 (fd 0)
12/18/16 11:30:39 - [main.c:44] [wlc] Failed to open X11 display
12/18/16 11:30:39 - [main.c:321] Starting sway version 0.11-rc3 (2016-12-17, branch "HEAD")

12/18/16 11:30:39 - [main.c:150] Linux blank 4.9.0 #1 SMP Mon Dec 12 09:31:42 EST 2016 x86_64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz GenuineIntel GNU/Linux
12/18/16 11:30:39 - [main.c:122] Contents of /etc/lsb-release:
12/18/16 11:30:39 - [main.c:129] DISTRIB_ID="Gentoo"
12/18/16 11:30:39 - [main.c:122] Contents of /etc/os-release:
12/18/16 11:30:39 - [main.c:129] NAME=Gentoo
12/18/16 11:30:39 - [main.c:129] ID=gentoo
12/18/16 11:30:39 - [main.c:129] PRETTY_NAME="Gentoo/Linux"
12/18/16 11:30:39 - [main.c:129] ANSI_COLOR="1;32"
12/18/16 11:30:39 - [main.c:129] HOME_URL="https://www.gentoo.org/"
12/18/16 11:30:39 - [main.c:129] SUPPORT_URL="https://www.gentoo.org/support/"
12/18/16 11:30:39 - [main.c:129] BUG_REPORT_URL="https://bugs.gentoo.org/"
12/18/16 11:30:39 - [main.c:122] Contents of /etc/gentoo-release:
12/18/16 11:30:39 - [main.c:129] Gentoo Base System release 2.3
12/18/16 11:30:39 - [main.c:107] PATH=/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/4.9.3
12/18/16 11:30:39 - [main.c:107] LD_LOAD_PATH=(null)
12/18/16 11:30:39 - [main.c:107] LD_PRELOAD_PATH=(null)
12/18/16 11:30:39 - [main.c:107] LD_LIBRARY_PATH=OFF
12/18/16 11:30:39 - [main.c:107] SWAY_CURSOR_THEME=(null)
12/18/16 11:30:39 - [main.c:107] SWAY_CURSOR_SIZE=(null)
12/18/16 11:30:39 - [main.c:107] SWAYSOCK=(null)
12/18/16 11:30:39 - [main.c:107] WLC_DRM_DEVICE=(null)
12/18/16 11:30:39 - [main.c:107] WLC_SHM=(null)
12/18/16 11:30:39 - [main.c:107] WLC_OUTPUTS=(null)
12/18/16 11:30:39 - [main.c:107] WLC_XWAYLAND=(null)
12/18/16 11:30:39 - [main.c:107] WLC_LIBINPUT=(null)
12/18/16 11:30:39 - [main.c:107] WLC_REPEAT_DELAY=(null)
12/18/16 11:30:39 - [main.c:107] WLC_REPEAT_RATE=(null)
12/18/16 11:30:39 - [main.c:107] XKB_DEFAULT_RULES=(null)
12/18/16 11:30:39 - [main.c:107] XKB_DEFAULT_MODEL=(null)
12/18/16 11:30:39 - [main.c:107] XKB_DEFAULT_LAYOUT=(null)
12/18/16 11:30:39 - [main.c:107] XKB_DEFAULT_VARIANT=(null)
12/18/16 11:30:39 - [main.c:107] XKB_DEFAULT_OPTIONS=(null)

.....

12/18/16 12:26:26 - [layout.c:918] Arranging 0x10c7f00 horizontally
12/18/16 12:26:26 - [layout.c:922] Calculating arrangement for 0x10cf670:3 (will scale 1920.000000 by 1.000000)
12/18/16 12:26:26 - [layout.c:786] Arranging layout for 0x10cf670 (null) 1920.000000x1055.000000+0.000000,25.000000
12/18/16 12:26:26 - [layout.c:786] Arranging layout for 0x10c8500 A31 Midterm 2015.pdf 1920.000000x1055.000000+0.000000,25.000000
12/18/16 12:26:26 - [layout.c:858] Set view to 1920 x 1055 @ 0, 25
12/18/16 12:26:26 - [debug_log.c:94] Arranging layout for 0x10fea50 (WORKSPACE '4')
12/18/16 12:26:26 - [layout.c:786] Arranging layout for 0x10fea50 4 1920.000000x1055.000000+0.000000,25.000000
12/18/16 12:26:26 - [layout.c:826] -> Found panel for this workspace: 1920x25, position: 0
12/18/16 12:26:26 - [layout.c:848] Arranging workspace '4' at 0.000000, 25.000000
12/18/16 12:26:26 - [layout.c:918] Arranging 0x10fea50 horizontally
12/18/16 12:26:26 - [layout.c:922] Calculating arrangement for 0x10b13c0:3 (will scale 1920.000000 by 1.000000)
12/18/16 12:26:26 - [layout.c:786] Arranging layout for 0x10b13c0 (null) 1920.000000x1055.000000+0.000000,25.000000
12/18/16 12:26:26 - [layout.c:786] Arranging layout for 0x10fd900 Messenger - Chromium 1920.000000x1055.000000+0.000000,25.000000
12/18/16 12:26:26 - [layout.c:858] Set view to 1920 x 1055 @ 0, 25
focus:R      |(0x638db0)(p:(nil)   )(f:0xb57840)(h:18446744073709551615)Type:root|layout:-    |w:1920|h:1080|x:   0|y:   0|g:  0|vis:t|children: 1|name:root
|focus:X     |(0xb57840)(p:0x638db0)(f:0xa05580)(h: 1)Type:op  |layout:-    |w:1920|h:1080|x:   0|y:   0|g: -1|vis:t|children: 4|name:eDP-1
|-focus:X    |(0xb8eec0)(p:0xb57840)(f:0x18f0d20)(h:18446744073709551615)Type:ws  |layout:Horiz|w:1920|h:1055|x:   0|y:  25|g: -1|vis:f|children: 1|name:1
|--focus:X   |(0x18f0d20)(p:0xb8eec0)(f:0x1105ed0)(h:18446744073709551615)Type:cont|layout:Tab  |w:1920|h:1055|x:   0|y:  25|g: -1|vis:f|children: 1|name:(null)
|---focus:X  |(0x1105ed0)(p:0x18f0d20)(f:(nil)   )(h: 4)Type:view|layout:-    |w:1920|h:1055|x:   0|y:  25|g: -1|vis:f|children: 0|name:shana@blank:~
|-focus:W    |(0xa05580)(p:0xb57840)(f:0x2cda000)(h:18446744073709551615)Type:ws  |layout:Horiz|w:1920|h:1055|x:   0|y:  25|g: -1|vis:t|children: 2|name:2
|--focus:X   |(0x10ddfe0)(p:0xa05580)(f:(nil)   )(h: 6)Type:view|layout:-    |w: 960|h:1055|x:   0|y:  25|g: -1|vis:t|children: 0|name:/home/shana/docu
|--focus:K   |(0x2cda000)(p:0xa05580)(f:(nil)   )(h: 8)Type:view|layout:-    |w: 960|h:1055|x: 960|y:  25|g: -1|vis:t|children: 0|name:Document Viewer
|-focus:X    |(0x10c7f00)(p:0xb57840)(f:0x10cf670)(h:18446744073709551615)Type:ws  |layout:Horiz|w:1920|h:1055|x:   0|y:  25|g: -1|vis:f|children: 1|name:3
|--focus:X   |(0x10cf670)(p:0x10c7f00)(f:0x10c8500)(h:18446744073709551615)Type:cont|layout:Tab  |w:1920|h:1055|x:   0|y:  25|g: -1|vis:f|children: 1|name:(null)
|---focus:X  |(0x10c8500)(p:0x10cf670)(f:(nil)   )(h: 7)Type:view|layout:-    |w:1920|h:1055|x:   0|y:  25|g: -1|vis:f|children: 0|name:A31 Midterm 2015
|-focus:X    |(0x10fea50)(p:0xb57840)(f:0x10b13c0)(h:18446744073709551615)Type:ws  |layout:Horiz|w:1920|h:1055|x:   0|y:  25|g: -1|vis:f|children: 1|name:4
|--focus:X   |(0x10b13c0)(p:0x10fea50)(f:0x10fd900)(h:18446744073709551615)Type:cont|layout:Tab  |w:1920|h:1055|x:   0|y:  25|g: -1|vis:f|children: 1|name:(null)
|---focus:X  |(0x10fd900)(p:0x10b13c0)(f:(nil)   )(h: 5)Type:view|layout:-    |w:1920|h:1055|x:   0|y:  25|g: -1|vis:f|children: 0|name:Messenger - Chro
12/18/16 12:26:26 - [bar.c:230] failed to dispatch wl: 32
12/18/16 12:26:26 - [bar.c:230] failed to dispatch wl: 32
12/18/16 12:26:26 - [bar.c:230] failed to dispatch wl: 32
12/18/16 12:26:26 - [bar.c:230] failed to dispatch wl: 32
12/18/16 12:26:26 - [bar.c:230] failed to dispatch wl: 32
12/18/16 12:26:26 - [bar.c:230] failed to dispatch wl: 32
12/18/16 12:26:26 - [bar.c:230] failed to dispatch wl: 32
12/18/16 12:26:26 - [bar.c:230] failed to dispatch wl: 32
12/18/16 12:26:26 - [bar.c:230] failed to dispatch wl: 32
12/18/16 12:26:26 - [bar.c:230] failed to dispatch wl: 32
12/18/16 12:26:26 - [bar.c:230] failed to dispatch wl: 32
12/18/16 12:26:26 - [bar.c:230] failed to dispatch wl: 32
12/18/16 12:26:26 - [bar.c:230] failed to dispatch wl: 32
ERROR: Unable to receive IPC response
12/18/16 12:26:26 - [main.c:46] [wlc] Parent exit (923)
12/18/16 12:26:26 - [main.c:46] [wlc] Restoring vt 1 (0x4) (fd 0)
[1085:1085:1218/122626:ERROR:x11_util.cc(87)] X IO error received (X server probably went away)

(spacefm:9710): Gdk-WARNING **: spacefm: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.

[1022:1022:1218/122626:ERROR:chrome_browser_main_extra_parts_x11.cc(62)] X IO error received (X server probably went away)
Received signal 11 SEGV_MAPERR 000000000968
#0 0x558e9021be3e <unknown>
#1 0x558e9021c1fb <unknown>
#2 0x7f3703da0d70 <unknown>
#3 0x7f370299d182 XInternAtoms
#4 0x558e9092c069 <unknown>
#5 0x558e90976bc5 <unknown>
#6 0x558e90976c65 <unknown>
#7 0x558e9097b03b <unknown>
#8 0x558e938459e4 <unknown>
#9 0x558e93845a37 <unknown>
#10 0x558e91c85401 <unknown>
#11 0x558e8fe78194 <unknown>
#12 0x558e8fe77419 <unknown>
#13 0x558e8ea7fbcc ChromeMain
#14 0x7f36f9a64630 __libc_start_main
#15 0x558e8ea7fa89 _start
  r8: 00000e178e704d10  r9: fffffffd538b8ab8 r10: fffff1eaddfb90a8 r11: 0000000000000246
 r12: 00000e178e72c750 r13: 0000000000000000 r14: 00007ffdf0462e40 r15: 00000e178e704d10
  di: 0000000000000000  si: 0000558e968d3c00  bp: 0000000000000000  bx: 0000000000000015
  dx: 0000000000000015  ax: 00000e178e704d10  cx: 0000000000000000  sp: 00007ffdf0462d70
  ip: 00007f370299d182 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000968
[end of stack trace]

```

**Comment by SirCmpwn** [comment] 2016-12-18 20:09
Duplicate of #992

**Closed by SirCmpwn** 2016-12-18 20:09 UTC
