### ISSUE TITLE
Double mouse when open urxvt

### ISSUE THREAD

**Issue by Fale** [SirCmpwn/sway#844] opened 2016-08-07 23:03 UTC
As soon as I started sway everything was ok. Then I opened urxvt and the mouse duplicated itself (one copy remained stuck where it was when I opened urxvt and the other is behaving normally.

I'm running sway 0.9. What other info could help?

**Comment by SirCmpwn** [comment] 2016-08-07 23:35
Duplicate of #759 discussed on IRC

**Closed by SirCmpwn** 2016-08-07 23:35 UTC
