### ISSUE TITLE
Launching sway from gdm leaves the login screen mouse visible 

### ISSUE THREAD

**Issue by Kunagi7** [SirCmpwn/sway#872] opened 2016-08-28 11:57 UTC
Since I first tried sway (back on v0.6), I've seen that launching it from gdm makes the mouse from the login visible. Right now I compile sway myself directly from master.
It's weird since if I do a screenshot via swaygrab I can't see it.
To "avoid" this issue when I login to sway I move the mouse to the bottom right corner to somehow hide it:
![img_20160828_135054](https://cloud.githubusercontent.com/assets/21224415/18033499/1ab0d7d6-6d27-11e6-85fb-97eb7942fbfd.jpg)
![img_20160828_140223](https://cloud.githubusercontent.com/assets/21224415/18033543/5feebf88-6d28-11e6-9367-1a8531f7aa8b.jpg)

Breeze cursor (sway), dot the gdm cursor.
I don't know if this is an issue from gdm or sway.
Launching sway from a tty works as expected, without a mouse cursor on the screen.
Is there any login manager which supports wayland sessions that doesn't have this problem?
I use Fedora 23 with mesa, I have an intel hd 4000.

**Comment by coderkun** [comment] 2016-08-28 12:29
Duplicate of #759.

**Closed** 2016-08-28 13:21 UTC
