### ISSUE TITLE
Rapidly scrolling in bar freezes sway

### ISSUE THREAD

**Issue by ilyaluk** [SirCmpwn/sway#1089] opened 2017-02-27 06:22 UTC
Steps to reproduce:

* Open at least two workspaces
* Rapidly scroll up and down in bar switching them (it's easy if you have touchpad)

Looks like [this call](https://github.com/SirCmpwn/sway/blob/master/swaybar/bar.c#L229) freezes swaybar.

Arch Linux, latest `sway-git`, `wlc-git`

**Comment by SirCmpwn** [comment] 2017-02-27 09:00
Duplicate of #892

**Closed by SirCmpwn** 2017-02-27 09:00 UTC
