### ISSUE TITLE
Dropdown menus stop working after 1st use

### ISSUE THREAD

**Issue by enarax** [SirCmpwn/sway#783] opened 2016-07-22 13:36 UTC
Hi,

I installed sway on a freshly installed Archlinux system. The configuration is pretty much default, and I'm running it in standalone wayland mode (no Xorg installed), it runs flawlessly.
However I noticed an issue with dropdown menus which occures regardless whether the app uses QT or GTK. Here's how to reproduce:

1. Install lxappearance (or google chrome or any other app that has dropdown menus) and open it.
2. Go to the Font tab.
3. Change Sub-pixel geometry or hinting to something else.
4. Try to repeat step 3.
5. You will notice that the dropdown menu is not visible anymore. It indeed works, if you start clicking around randomly above/below the dropdown button you will see that the value changes, you just can't see the dropdown itself. Also changing the value with the up-down arrows works too.

The QT application I checked with (qtconfig-qt4) produces the exact same result.

I have some linux admin skills but I'm not great when it comes to debugging and also this is my first experience with Wayland. If I can help you with some logs or something else, let me know what commands to run and I'll be happy to help.

Thank you

**Comment by enarax** [comment] 2016-07-22 13:40
With Google Chrome (for example trying to change the default search engine in the Settings / Settings / Search section) it does not work the 1st time either, instead the whole window flashes once (going to the unfocused state then back again immediately), and the dropdown flashes as well (as if it was dismissed right at the moment it was opened). For this reason clicking "in the air" does not work here (but the arrow keys do).

**Comment by 4e554c4c** [comment] 2016-07-22 17:28
duplicate of #571

**Closed** 2016-10-13 14:25 UTC
