### ISSUE TITLE
Unable to access menus, flickering while trying to open

### ISSUE THREAD

**Issue by soredake** [SirCmpwn/sway#301] opened 2015-12-13 14:48 UTC
https://u.pomf.io/vnmsmb.mp4
https://u.pomf.io/ngchfe.mp4
https://u.pomf.io/mutdqv.mp4
https://u.pomf.io/hmkkyd.mp4

**Comment by SirCmpwn** [comment] 2015-12-13 14:53
Are you up to date on everything? In particular, make sure you're up to date on both wlc and sway.

**Comment by fenque** [comment] 2015-12-13 14:55
Yes, all system is up to date.

**Comment by SirCmpwn** [comment] 2015-12-13 14:56
Could you humour me by recompiling wlc? This was a known bug that was fixed in https://github.com/Cloudef/wlc/commit/359cfe776a17a0fae5f8179e8a89e9b47256f602

**Comment by fenque** [comment] 2015-12-13 16:02
I recorded this videos after recompiling, so...

**Comment by SirCmpwn** [comment] 2015-12-13 16:03
Recompiling sway or wlc? What distro are you on?

**Comment by fenque** [comment] 2015-12-13 16:06
Yes, i recompile sway, wlc, and packages on which they depend after seeing a bug. Gentoo unstable.

**Comment by SirCmpwn** [comment] 2015-12-13 16:06
Which version of xwayland?

**Comment by fenque** [comment] 2015-12-13 16:28
1.17.4

**Comment by SirCmpwn** [comment] 2015-12-13 16:28
Can you try 1.18.0?

**Comment by fenque** [comment] 2015-12-14 12:39
Still flickering with 1.18.0.

**Comment by SirCmpwn** [comment] 2015-12-14 13:07
Strange. I can't reproduce. You're on your own here.

**Comment by joecool1029** [comment] 2015-12-15 19:50
I've had this issue for some weeks.  Chromium generates it easy enough, just hover over any tabs and you'll get flickering when it fails to display the tooltip (hover-over text).

**Comment by fgaz** [comment] 2015-12-31 18:02
Same here on every qt5 program. The menu either flickers or opens as a new window until I move the cursor.
I just recompiled wlc and sway.

**Comment by SirCmpwn** [comment] 2015-12-31 18:03
Unmanaged windows are pretty buggy in sway. I think they're the source of this and other problems.

**Comment by fgaz** [comment] 2016-01-01 22:51
I just installed orbment and the same thing happens. It's probably wlc.

**Comment by SirCmpwn** [comment] 2016-01-01 22:52
My current understanding of the issue is that the fault is shared between all three.

**Closed** 2016-10-27 12:57 UTC
