### ISSUE TITLE
Wireshark issues

### ISSUE THREAD

**Issue by crondog** [SirCmpwn/sway#602] opened 2016-04-25 09:55 UTC
There are a couple of issues with using wireshark-gtk with sway. Both could be related but not too sure.

Add the following to your config. Then open wireshark and then the open dialog
```
gaps edge_gaps off
gaps 50
new_window pixel 10
```
![2016-04-25-194606_swaygrab](https://cloud.githubusercontent.com/assets/1883383/14780103/a7a1dc1e-0b1e-11e6-9736-753e6d1700d6.png)

The next issue is that if you have wireshark floating and then open the open dialog. Notice how it is nowhere to be found.

In both cases wlc_view_get_type returns 0 which is strange since in i3 the open dialog is floating in both cases

**Comment by jarias** [comment] 2016-04-26 15:16
Same with libreoffice

`Linux Arch`
`Sway 0.5-2`
`wlc 0.0.2-1`

![2016-04-26-090420_swaygrab](https://cloud.githubusercontent.com/assets/119519/14823365/90e65c9a-0b8f-11e6-9e1c-20f3def90447.png)

**Comment by SirCmpwn** [comment] 2016-04-26 15:18
Ping @Cloudef

**Comment by zandrmartin** [comment] 2016-06-07 13:36
I've found this problem happens with all GTK dialogs.

**Comment by Cloudef** [comment] 2016-06-07 14:48
This could be that the window type property is assigned to the window after being mapped. Fortunately we now have view_properties_updated for updating window titles and such, and we can just use that to also inform about type updates.

**Comment by SirCmpwn** [comment] 2016-06-07 14:53
>This could be that the window type property is assigned to the window after being mapped.

That would suuuuuuck.

**Comment by Cloudef** [comment] 2016-06-07 14:54
That's just hypothesis. Fortunately I have wireshark here handy, so I cansee what happens.

**Comment by Cloudef** [comment] 2016-06-07 15:32
Ah, I realized wireshark is wayland native too. So wlc_view_get_type() returning 0 is normal in this case. I guess orbment handles this fine because it centers child windows on parent. (wlc_view_get_parent, which the dialogue is, it's not special in any other way inside wayland)

**Comment by SirCmpwn** [comment] 2016-06-07 15:33
Ah, I didn't realize `wlc_view_get_parent` is a thing. We should probably default views with a parent to floating.

**Comment by SirCmpwn** [comment] 2016-06-08 21:54
Duplicate of #604.

**Closed by SirCmpwn** 2016-06-08 21:54 UTC
