### ISSUE TITLE
sway refuses to switch between workspaces above certain speed

### ISSUE THREAD

**Issue by zetok** [SirCmpwn/sway#452] opened 2016-01-17 18:52 UTC
When I'm trying to continuously switch between workspaces, sway refuses to switch between workspaces if after switching to workspace, subsequent switch happens <~150ms since switch. This value is at best unreliable - it's easier to reproduce just by switching several times (although switches still have to happen quite fast).

Reproducible: Always

Steps to reproduce:
1. Switch to workspace2 from workspace1
2. Switch to workspace1
3. Repeat steps 1-2 quickly enough to trigger the bug.

**Comment by mikkeloscar** [comment] 2016-03-18 20:15
I'm pretty sure this happens because sway doesn't allow you to hold down `$mod+1` and then click on `2` to switch to workspace 2 (this is possible in i3).

When you try to switch quickly like that, you most likely press down one key before you release the other. So it seems like it's slow, but sway is just blocking the binding because you are pressing down more keys than expected. I bet you can make it switch quite fast if you really think about lifting your finger off the key, before pressing the next one :)

We need to make sway understand our gentle human touch. I'll look into it.

**Comment by SirCmpwn** [comment] 2016-03-18 20:17
If the source of the problem is what you suggest, I don't want to fix it. One of the advantages of sway over i3 is that key bindings aren't based on modifiers. In i3 you can't have mod+1+2 do something distinct from mod+1 or mod+2, but in sway you can. I want to keep it that way. Key bindings are matched based on the current of the keyboard state machine and that shouldn't change.

**Comment by mikkeloscar** [comment] 2016-03-18 22:52
It would still be possible to have `$mod+1+2` if the binding exists, but if it doesn't then you could use the "trick" that i3 uses so it feels more natural (for people with slow fingers lol). I would prefer it that way as I often have a quick peek at another workspace, and sometimes I fail to switch back quick because of this.

But I can definitely understand your argument, I just don't think `$mod+1+2` behaving like `$mod+2` is a problem, but there might be some other cases where it's annoying?

Either way, that's my 2 cents.

**Comment by SirCmpwn** [comment] 2016-03-18 23:21
Well, think about stacking modifiers as well (in sway modifiers are treated as normal keys). Would you want mod+shift+s to behave differently than mod+s? In my own config I depend on there being a difference.

**Comment by mikkeloscar** [comment] 2016-03-18 23:45
I don't think that's a problem. The way it should work imo is:
If you press mod+Shift+s and the binding exists then that will win over mod+s. However, if you press mod+shift+s and that binding doesn't exist, then it would be treated as mod+s.

**Comment by SirCmpwn** [comment] 2016-03-19 00:00
That seems fair. After playing around with sway's current keyboard handling, I also don't see any reason to allow `$mod+1+2` and `$mod+1` to coexist.

**Comment by SirCmpwn** [comment] 2016-03-19 13:12
Fixed in #523, thanks @mikkeloscar

**Closed by SirCmpwn** 2016-03-19 13:12 UTC
