### ISSUE TITLE
Cannot interact with certain modal views

### ISSUE THREAD

**Issue by crondog** [SirCmpwn/sway#505] opened 2016-03-06 01:31 UTC
Part of the font selection modal view from lxappearance is unselectable.

Steps to reproduce:
* Open lxappearance
* Click the font selection box
* You are now unable to move/resize the window from the bottom and you are unable to click the OK and Cancel buttons

This works as expected inside wlc/example

**Comment by crondog** [comment] 2016-03-09 11:00
An update on this: If lxappearance is set to floating, and then you open the font selection you are able to resize of click the buttons

**Comment by SirCmpwn** [comment] 2016-03-11 13:58
I can reproduce this and have similar issues for many other kinds of windows. I will investigate this soon.

**Comment by mikkeloscar** [comment] 2016-03-30 08:18
This problem is more clearly exposed with borders enabled:

![2016-03-30-101713_swaygrab](https://cloud.githubusercontent.com/assets/128566/14135986/c20a5aa4-f660-11e5-8210-fe412f467fc8.png)

**Comment by SirCmpwn** [comment] 2016-03-30 11:49
Thanks. Window borders does reveal a lot about this problem. Pulled in @Cloudef, since I'm betting this is a wlc thing.

**Comment by crondog** [comment] 2016-03-30 11:49
It looks like the floating view has an offset of the parent view origin.

**Comment by crondog** [comment] 2016-03-30 11:50
But the borders are correctly calculated

**Comment by SirCmpwn** [comment] 2016-03-30 11:51
Right. I'm thinking that wlc is giving us one geometry for the window and rendering it in a different place. It's probably more subtle than that, though, because interactivity with these windows is weird.

**Comment by Cloudef** [comment] 2016-03-30 11:52
Both parented view's and subsurfaces have special logic. If this is either one of them, I would not be surprised if there was bugs. If input coordinates are wrong, then the surface is not rendered in correct place or vice versa.

**Comment by Cloudef** [comment] 2016-03-30 11:52
@SirCmpwn Did you guys use wlc_get_visible_geometry that was recently added for visual stuff though?

**Comment by crondog** [comment] 2016-03-30 11:55
Doing the below will set the floating view to the parents x,y. Not sure how to fix it yet though
```
diff --git a/sway/container.c b/sway/container.c
index 21a929b..75eb8c1 100644
--- a/sway/container.c
+++ b/sway/container.c
@@ -311,8 +311,8 @@ swayc_t *new_floating_view(wlc_handle handle) {
        wlc_view_get_visible_geometry(handle, &geometry);

        // give it requested geometry, but place in center
-       view->x = (swayc_active_workspace()->width - geometry.size.w) / 2;
-       view->y = (swayc_active_workspace()->height- geometry.size.h) / 2;
+       view->x = 0;
+       view->y = 0;
        view->width = geometry.size.w;
        view->height = geometry.size.h;
```

**Comment by SirCmpwn** [comment] 2016-03-30 11:55
It uses sway's internal state for that view, which is calculated by sway and handed to wlc_view_set_geometry.

**Comment by mikkeloscar** [comment] 2016-03-30 12:06
We only use `wlc_view_get_visible_geometry` now with the border stuff merged fwiw. (I kind of forgot about this, but it is the right thing to do anyway).

Doesn't solve this problem directly though.

**Comment by SirCmpwn** [comment] 2016-03-30 12:08
Really? So far as I can tell, that's not the case (after reading through the relevant code).

**Comment by mikkeloscar** [comment] 2016-03-30 12:19
It was sneaked in here: https://github.com/SirCmpwn/sway/commit/5a13cb0ed136906a4370235214601b0129548c49#diff-5125e6a182d823f6a2ad1c0b7a576892L907 and 2 other places in that commit, to replace `wlc_view_get_geometry`

**Comment by SirCmpwn** [comment] 2016-03-30 12:19
Ah. Cool.

**Comment by SirCmpwn** [comment] 2016-03-31 13:56
Fixed by https://github.com/Cloudef/wlc/issues/145

**Closed by SirCmpwn** 2016-03-31 13:56 UTC
